clase-junio14/blog/config/routes.rb
Rails.application.routes.draw do

  resources :posts, only: [:index, :show] do
    resources :comments
  end

  resources :users, except: [:index, :create, :new] do
    resources :posts, except: [:index]
    member do
      get 'posts'
    end
  end
  devise_for :users, path: 'auth'

  root 'index#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

clase-junio14/blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

clase-junio14/blog/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :content, length: {in: 1..140}, presence: true
  validates :title, length: {in: 1..100}


end

clase-junio14/blog/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
  has_many  :posts
end

clase-junio14/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

clase-junio14/blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:destroy]
  respond_to :js

  def index
    post = Post.find params[:post_id]
    @comments = post.comments
    render json: @comments
  end

  def create
    safe_params = params.require(:comment).permit(:content, :post_id)
    @comment = Comment.new safe_params
    @post = Post.find params[:post_id]
    user = @post.user
    @post.comments.push @comment
    @comment.save
    redirect_to user_post_path(user, @post)
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def show
    post = Post.find params[:post_id]
    comment = post.comments.find params[:id]
    render json: comment
  end

  def update
  end

  def destroy
    @post = Post.includes(:comments).find params[:post_id]
    Comment.destroy params[:id]
    head :no_content
  end

end

clase-junio14/blog/app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

clase-junio14/blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all
  end

  def create
    safe_params = params.require(:post).permit(:title, :content)
    @post = Post.new safe_params
    @post.user = current_user
    if @post.save
      if current_user.posts.length == 1
        FirstPostMailer.first_post_emaildle(current_customer).deliver_now
      end
      redirect_to user_post_path(current_user, @post)
    else
      render :new
    end
  end

  def new
    @post = Post.new
    respond_to do |format|
      format.html
      format.js { render partial: 'form', content_type: 'text/plain' }
    end
  end

  def edit

  end
  def show
    @post = Post.includes(:comments).find params[:id]
    @comments = @post.comments
    @comment = Comment.new

#    respond_to do |format|
#      format.html
#      format.js { render partial: 'comments', content_type: 'text/plain' }
#    end
  end

  def update

  end
  def destroy

  end
end

clase-junio14/blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def edit
  end
  def show
  end
  def update
  end
  def posts
    #current_user
    @posts = User.includes(:posts).find(current_user.id).posts
  end
  def destroy
  end
end

clase-junio14/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

clase-junio14/blog/app/helpers/comments_helper.rb
module CommentsHelper
end

clase-junio14/blog/app/helpers/posts_helper.rb
module PostsHelper
end

clase-junio14/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "see all posts", user_posts_path(current_user)%>
      <%= link_to "Logout", destroy_user_session_path, method: 'delete'%>
    <%else%>
        <%= link_to "Create an account", new_user_registration_path%>
    <%end%>
    <%= yield %>
  </body>
</html>

clase-junio14/blog/app/views/posts/_form.html.erb
<h1> New Post </h1>

<%= form_for @post, url: user_posts_path(current_user), class: "new_post" do |f| %>


  <div class="field">
  <%=f.label :title, "Title"%>
  <%=f.text_field :title, id: "title-field"%>
  </div>

  <div class="field">
  <%=f.label :content, "Content"%>
  <%=f.text_field :content, id: "content-field"%>
  </div>

  <%=f.submit "Create post", :disable_with => 'Creating...' %>

<%end%>

<script type="text/javascript">
  $(document).on('turbolinks:load', function(){
    new PostView()
  })
</script>

clase-junio14/blog/app/views/posts/index.html.erb
<% if @posts.empty? %>
  <h1>There is no posts</h1>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1"></div>
      <h1>Blogs</h1>
    </div>
  </div>
  <div class="col-sm-10 col-sm-offset-1">
    <table class="table table-hover">
      <thead>
        <th>Title</th>
        <th>Content</th>
      </thead>
      <tbody>
        <% @posts.each do |post|%>
          <tr>
          <td><%= post.title %></td>
          <td><p><%= post.content %></p></td>
          <td><%=link_to "ver post", post_path(post)%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<div>

clase-junio14/blog/app/views/posts/new.html.erb
<%= render "form" %>

clase-junio14/blog/app/views/posts/new.js.erb
var form = $('<%= escape_javascript render "form" %>')
$('.new-form').append(form)

clase-junio14/blog/app/views/posts/show.html.erb
<br>
<h3><strong><%=@post.title%></strong><h3>
<h5><%=@post.content%></h5>

<div class="commentary">

</div>

<%= form_for [@post, @comment] do |f| %>
  <div class="comment-content">
  <%=f.text_area :content, id: "comment-content-field", size: "60x3"%>
  </div>
  <%=f.submit "Comment", :disable_with => 'Creating...' %>
<%end%>

<script type="text/javascript">
  $(document).on('turbolinks:load', function(){
    loadCommentsAsync()
    //loadCommentsJavascript()
  })

  $(document).on('click', '.delete', function(){
    var id = $(this).attr('data-id')
    console.log(id)
    $.ajax({
      type: "DELETE",
      url: "<%=post_comments_path @post%>" +"/"+ id
    }).done(function(data){
      alert('Ahora sí!')
    }).fail(function(error){
      alert('No se eliminó')
    })
  })

  function loadCommentsAsync(){
    $.ajax({
      type: "GET",
      contentType: 'application/json',
      url: "<%=post_comments_path @post%>"
    }).done(function(data){
      drawComments(data)
    })
  }
  function drawComments(data){
    data.forEach(function(object){
      var dest = '<a class="delete" data-id="' + object.id + '" href="#" data-remote="true">Eliminar</a>'
      $('.commentary').append(object.content +'  '+ dest + '<br>')
    })
  }

    // function loadCommentsJavascript(){
    //   $.ajax({
    //     type: "GET",
    //     contentType: 'application/javascript',
    //     url: "<%=post_comments_path @post%>"
    //   }).done(function(data){
    //     drawComments(data)
    //   })
    //   function drawComments(data){
    //     data.forEach(function(object){
    //       $('.commentary').append(object.content + '<br>')
    //     })
    //   }

</script>