clase16/makeitreal/config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'index', to: 'index#index'
  root 'index#index'



  get 'holi/crear'

  get 'holi/actualizar'

  get 'holi/ver(/:nombre)', to: 'holi#ver' #El (/:nombre) es para que sea opcional el link, si no ponen nombre tambien funciona enviando un nil

  get 'holi/products' => 'holi#products', as: 'products1' #Convierte el nombre de la ruta a solo products

##### EJERCICIO PONER LOS ELEMENTOS  DE LA LISTA COMO LINKS

  #get 'products' , to: 'lista#list' ## Se puede hacer de las dos maneras
  get 'products'=> 'list#list_products'

  get 'products/:nombre'=> 'list#product', as: 'item'

  #get 'products/manzanas', to: 'list#manzanas', as: 'manzanas'
  #get 'products/limones', to: 'list#limones', as: 'limones'
  #get 'products/duraznos', to: 'list#duraznos', as: 'duraznos'
  #get 'products/peras', to: 'list#peras', as: 'peras'
end

clase16/makeitreal/app/controllers/holi_controller.rb
class HoliController < ApplicationController
  def crear
  end

  def actualizar
  end

  def ver
    @nombre = params[:nombre]
    render layout: "custom_product"
  end

  def products
    @products =[
      {name: 'Audifonos', precio: 49999},
      {name: 'Reloj', precio: 94984}
    ]
    render json: @products, status: :not_found
  end

end

clase16/makeitreal/app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
  def root
    render 'holi'
  end
end

clase16/makeitreal/app/controllers/list_controller.rb
class ListController < ApplicationController
  def list_products
    @lista=lista_productos
  end
  def lista_productos
    [{name: 'manzanas'},{name: 'limones'}, {name: 'duraznos'}, {name: 'peras'}]
  end
  def product
    @lista=lista_productos
    @seleccion = @lista.find do |producto|
      producto == params[:nombre]
    end
  end
end

clase16/makeitreal/app/helpers/holi_helper.rb
module HoliHelper
end

clase16/makeitreal/app/views/holi/_minicart.html.erb
<h2>Minicart</h2>

<ul>
  <li>product1</li>
  <li>product2</li>
  <li>product3</li>
  <li>product4</li>
  <li>product5</li>
  <li>product6</li>
</ul>

clase16/makeitreal/app/views/holi/actualizar.html.erb
<h1>Holi#actualizar</h1>
<p>Find me in app/views/holi/actualizar.html.erb</p>

clase16/makeitreal/app/views/holi/crear.html.erb
<h1>Holi#crear</h1>
<p>Find me in app/views/holi/crear.html.erb</p>

clase16/makeitreal/app/views/holi/ver.html.erb
  <% content_for :title do %>
  Mac
  <%end %>

  <% render 'minicart'%>

<% content_for :top_bar do %>
<h1> This is a top bar</h1>
<% end %>

<h1>Holi#ver</h1>
<p><%=@nombre%></p>

clase16/makeitreal/app/views/index/index.html.erb
<h1>Hola desde rails</h1>

clase16/makeitreal/app/views/list/duraznos.html.erb
<h1>Duraznos</h1>

clase16/makeitreal/app/views/list/limones.html.erb
<h1>Limones</h1>

clase16/makeitreal/app/views/list/list_products.html.erb
<ul>
  <% @list.each do |item| %>
  <li><%= link_to item[:name], item_path %></li>
  <%end%>
</ul>

clase16/makeitreal/app/views/list/manzanas.html.erb
<h1>Manzanas</h1>

clase16/makeitreal/app/views/list/product.html.erb
<h1><%=@seleccion[:name] %></h1>